Switch from floryn90/hugo to ghcr.io/gohugoio/hugo image
Switch from floryn90/hugo to ghcr.io/gohugoio/hugo image

The site build using docker-compose fails since floryn90/hugo v0.134.3:

```
Error: error building site: failed to acquire a build lock: open /src/.hugo_build.lock: permission denied

Cause: The Alpine image has switched from root user to hugo user:

Florin-Lungu/docker-hugo@b261630
```

Fix: Switch to offical ghcr.io/gohugoio/hugo image that doesn't have the problem.