Switch from floryn90/hugo to hugomods/hugo image
The site build fails since floryn90/hugo v0.134.3:

```
Error: error building site: failed to acquire a build lock: open /src/.hugo_build.lock: permission denied
```

Cause: The Alpine image has switched from root user to hugo user:

https://github.com/floryn90/docker-hugo/commit/b26163074781850eba0151306837c55f8a2b5b1e

Fix: Switch to hugomods/hugo image that still runs as root user.

The hugomods/hugo:std-exts image has git included making our Dockerfile obsolete.